<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Gestión CUAD</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">        
       
    </head>
    <body>

		<header>
			<div class="clearfix">
				<img class="img-responsive pull-right" src="images/telmex_logo.jpg" alt="TELMEX">
				<img class="img-responsive pull-left" src="images/gestion_cuad.jpg" alt="Gestión CUAD">
			</div>
		</header>
			
		<!-- Second navbar for categories -->
		<nav class="navbar navbar-default">
			<div class="">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand hidden visible-xs" href="#">Menu</a>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Aplicaciones</a></li>
						<li ><a href="#"><i class="fa fa-fw fa-building"></i>Empresas</a></li>
						<li class="active"><a href="admins"><i class="fa fa-group"></i> Perfiles</a></li>    <li ><a href="#"><i class="glyphicon glyphicon-list-alt"></i> Logs</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Carlos Román<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#" id="view-manuals"><i class="fa fa-book fa-fw"></i> Manual</a></li>
								<li>
									<a href=""><i class="fa fa-key fa-fw"></i> Cambiar Contraseña</a>
								</li>
								<li>
									<a href="login.html"><i class="fa fa-fw fa-power-off"></i> Cerrar sesión</a>
								</li>
							</ul>
						</li>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container -->
		</nav><!-- /.navbar -->
			
		<div class="wrapper">
			<div class="container">
				<div class="page-header">
					<!--<h3>Perfiles <small>Listado de los operadores del sistema</small></h3>-->
				</div>
				<button class="btn btn-primary" type="button" id='addProfile' data-toggle="modal" data-target="#modal-add-user">
					<span class="glyphicon glyphicon-plus-sign"></span> Agregar Perfil
				</button>
                            
                            <select>
                                <option value="">- - - Seleccione - - -</option>
                            <?php foreach ($catServicios as $tabla) : ?>
                           <option value="<?php echo $this->escapehtml($tabla->NUMERO_PARTE);?>"><?php echo $this->escapehtml($tabla->NUMERO_PARTE);?></option>
                           <?php endforeach; ?>
                            </select>
				
		
	</body>
</html>