<?php   
  
use Zend\Session\Container;

$user_session = new Container('user');         
?>        
<div class="wrapper">   
			<div class="container">
				<div class="page-header">
					<h3>Empresas <small>Detalle de empresas registradas</small></h3>
				</div>
				
				<div class="row">
			     <div class="col-lg-3 col-md-6">     
			       <a href="<?php echo $this->url('enterprise', array('action' => 'altas')); ?>" title="">	  
                    <div class="panel panel-primary">  
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-industry fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">                                    
                                    <div>Nueva Empresa!</div>  
                                </div>  
                            </div>
                        </div>
                       
                            <div class="panel-footer">
                                <span class="pull-left">Agregar una Empresa</span>   
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                    </div>
                    </a>
                 </div>	  
				</div>  
				
				
				<div class="datagrid">
					<table id="tableGrid" class="table table-responsive responsive table-stripe">
						<thead>  
							<tr>  
								<th class="text-center">Nombre</th>  
								<th class="text-center">RFC</th>
								<th class="text-center">Servicio</th>
								<th class="text-center">Project Manager</th>								
								<th class="text-center">Número Extensiones</th>   
								<th class="text-center">Acciones</th>        
							</tr>
						</thead>
						<tbody>
                            <?php foreach ($empresas as $tabla) : ?>
							<tr>
								<td><?php echo $this->escapehtml($tabla['COMPANY']);?></td>       
								<td><?php echo $this->escapehtml($tabla['CUSTOMER_ID']);?></td>  
								<td><?php  if(!empty($tabla['TIPOSERVICIO'])){
									
									foreach($tabla['TIPOSERVICIO'] as $tiposervicio){
										if($tiposervicio[0]==1){
										 echo "CUAD-CISCO"."<br>";	
										}else if($tiposervicio[0]==2){
										 echo "CUAD-BROADSOFT"."<br>";    	
										}
										
									}
									      
								}
								?></td>
								<td><?php echo $this->escapehtml($tabla['CORREOPM']);?></td>  
								<td><?php echo $this->escapehtml($tabla->CUSTOMER_SINCE);?></td>           								
								<td class="text-center">
									<a href="<?php echo $this->url('enterprise', array('action' => 'altas', 'id' =>$tabla["CUSTOMER_ID"])); ?>" class="btn-accion btn-primary" title="Editar">     
										<i class="halflings-icon fa fa-pencil"></i>          
									</a>  
								    <?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") { ?>   
                                    <a data-id="<?php echo $this->escapehtml($tabla['CUSTOMER_ID']);?>" data-toggle="modal" data-target="#myModal"  class="btn-accion btn-danger borrar" 
                                    	onclick="getCustomer('<?php echo $this->escapehtml($tabla['CUSTOMER_ID']);?>');" title="Eliminar">   
										<i class="halflings-icon fa fa-trash"></i>         
									</a> 
									<?php  } ?>
									<a href="<?php echo $this->url('sites', array('action' => 'index', 'id' =>$tabla['CUSTOMER_ID'], 'kind' =>'find')); ?>"  class="btn-accion btn-info" title="Sitios">   
										<i class="halflings-icon fa fa-building"></i>          
									</a>   
                                    <?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") { ?>
                                    <a href="<?php echo $this->url('userpm', array('id' =>$tabla['CUSTOMER_ID'])); ?>" class="btn-accion btn-success" title="Asignar PM">   
										<i class="halflings-icon fa fa-user-plus"></i>                   
									</a>   	  
								   <?php  } ?>
								                                   
									<a href="<?php echo $this->url('enterprise', array('action' => 'detalle', 'id' =>$tabla['CUSTOMER_ID'])); ?>" class="btn-accion btn-warning" title="Detalles Empresa">   
										<i class="halflings-icon fa fa-eye"></i>            
									</a>   
								</td>   
							</tr>
                            <?php endforeach; ?>
						</tbody>
                   </table>
				</div> 
				
				<!--Load-->   
			    <div id="ark_loader-empresas" class="ark_loader">  
			      <span>CARGANDO</span>
			      <span>
			        <div class="sk-fading-circle">
			          <div class="sk-circle1 sk-circle"></div>
			          <div class="sk-circle2 sk-circle"></div>
			          <div class="sk-circle3 sk-circle"></div>
			          <div class="sk-circle4 sk-circle"></div>
			          <div class="sk-circle5 sk-circle"></div>
			          <div class="sk-circle6 sk-circle"></div>
			          <div class="sk-circle7 sk-circle"></div>
			          <div class="sk-circle8 sk-circle"></div>
			          <div class="sk-circle9 sk-circle"></div>
			          <div class="sk-circle10 sk-circle"></div>
			          <div class="sk-circle11 sk-circle"></div>
			          <div class="sk-circle12 sk-circle"></div>
			        </div>
			      </span>  
			    </div>  
			    <!--load-->
				
				
				
				       
			</div>
		</div>



<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <form name="borraEmpresa" id="borraEmpresa" method="post" action="">      
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Borrar Empresa</h4>
      </div>
      <div class="modal-body">
      <p>¿Está seguro de eliminar la empresa con RFC  <span style="font-weight: bold" name="RFC" id="RFC"></span>?</p>
      </div>
        <div class="errorMessage text-danger"><span id="erroridEmpresa"></span></div>
        <input type="hidden" name="idEmpresa" id="idEmpresa"></input>
      <div class="modal-footer">
          
          <button id="borrando" type="submit" class="btn btn-primary">Eliminar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
    </form>
  </div>  
</div>
  
<script type="text/javascript">

   $(window).load(function() {
		// Animate loader off screen
		$("#ark_loader-empresas").fadeOut("slow");;         
   });
    
    $(document).ready(function(){
	     $('.borrar').click(function() {                    
		     var $this=$(this);     
		                    
		     var ID = $this.attr('data-id');
		     // alert(ID);
	                     
	                    
	     });
   });
</script>   
                 
       <?php 
   echo $this->headScript() 
  ->prependFile($this->basePath('/js/empresas.js'));
 
           
    
