
			<div class="row">
			  
                <div class="col-md-12">
				
                    <div class="error-template">
						
						<h1>Oops!</h1>
						<h2>Recurso No Encontrado</h2>
						
						<div class="error-details">¡Lo sentimos, ha ocurrido un error inesperado!</div>
						
						<div class="error-actions">
							<a href="dashboard" class="btn btn-default btn-lg"><span class="fa fa-home"></span> Ir al Inicio </a>
						</div>
				  
						<div class="sytem-messages">
							
							  				
							<!--<p>The requested controller was unable to dispatch the request.</p>
							<dl>
								<dt>Controller:</dt>
								<dd>Application\Controller\Index</dd>
							</dl>---->       
							<h3><?php echo $this->message ?></h3>  
						</div>
						
					</div>
					
				</div>
				
            </div>
			
        