<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Form\LoginForm'             => __DIR__ . '/src/Application/Form/LoginForm.php',
    'Application\Model\User'                 => __DIR__ . '/src/Application/Model/User.php',
    'Application\Model\MyAuthStorage'        => __DIR__ . '/src/Application/Model/MyAuthStorage.php',
    'Application\Controller\LoginController' => __DIR__ . '/src/Application/Controller/LoginController.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
);
