<?php echo $this->doctype(); 

use Zend\I18n\Translator\Translator;

$translator = new Translator();
//$translator->addTranslationFile($type, $filename, $textDomain, $locale);  

?>


<html lang="es">  
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
			  
			echo $this->headTitle('Sistema de Gestión CUAD'); 
        ?>

        
        <!-- Le styles -->

                <!--[if lt IE 9]><script type="text/javascript" src="libs/html5shiv.min.js"></script><![endif]-->
		<!--[if lt IE 9]><script type="text/javascript" src="libs/respond.min.js"></script><![endif]-->

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/images/faviconVsys16x16.png'))
		                ->prependStylesheet($this->basePath('css/error.css'))  
                        ->prependStylesheet($this->basePath('libs/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('libs/bootstrap/css/bootstrap.min.css'))                        
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,300,300italic,900,500,500italic,700italic,900italic')

                
                
                ?>

        <!-- Scripts -->
        
           <?php
       echo $this->headScript()       
                    ->prependFile($this->basePath('libs/bootstrap/js/bootstrap.min.js')) 
                    ->prependFile($this->basePath('libs/prefixfree.min.js'))
                    ->prependFile($this->basePath('libs/jquery/jquery-1.11.3.min.js'))             
        ; ?>


    </head>
    <body>
      
      
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
             
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
  