<?php echo $this->doctype(); 

?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');   

    
     echo $this->headTitle('Sistema de Gestión CUAD');  
   ?>



        
        <!-- Le styles -->
        <?php 


        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/faviconVsys16x16.png'))  
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,300,300italic,900,500,500italic,700italic,900italic')
                        ->prependStylesheet($this->basePath().'/libs/bootstrap/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath().'/libs/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath().'/libs/alertifyjs/css/alertify.min.css')
                        ->prependStylesheet($this->basePath().'/libs/alertifyjs/css/themes/bootstrap.min.css')
                        ->prependStylesheet($this->basePath().'/libs/spinkit/spinkit.css')
                        ->prependStylesheet($this->basePath() . '/css/login.css')
                
                ?>
         
        <!-- Scripts -->
        <?php
        
        
        
        echo $this->headScript()
            ->appendFile($this->basePath('/libs/jquery/jquery-1.11.3.min.js'))
            ->appendFile($this->basePath('/libs/bootstrap/js/bootstrap.min.js'))
            ->appendFile($this->basePath('/libs/prefixfree.min.js'))
            ->appendFile($this->basePath('/libs/jquery-validation/jquery.validate.min.js'))
            ->appendFile($this->basePath('/libs/jquery-validation/localization/messages_es.min.js'))     
            ->appendFile($this->basePath('/libs/alertifyjs/alertify.min.js')) 
            
           
        ; ?>

    </head>
    <body>
      
      
            <?php echo $this->navigation; ?>
            <?php echo $this->content; ?>

           
        <!-- /container -->
        <?php 
        echo $this->inlineScript();  	
		 ?>
        
        
    </body>
</html>
