<?php echo $this->doctype();

 use Zend\Session\Container;
new Zend\Escaper\Escaper('utf-8');     
 $user_session = new Container('user');
 

$uri = $this->serverUrl(true);
$array=  explode('/', $uri);
$largo=count($array);
$menu=$array[$largo-1];  
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
			
			echo $this->headTitle('Sistema de Gestión CUAD'); 
        ?>
   
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/images/faviconVsys16x16.png'))
                          ->prependStylesheet($this->basePath('css/main.css'))
						  ->prependStylesheet($this->basePath('css/styles.css'))       
                          ->prependStylesheet($this->basePath('libs/spinkit/spinkit.css'))
                          ->prependStylesheet($this->basePath('libs/alertifyjs/css/themes/bootstrap.min.css'))
                          ->prependStylesheet($this->basePath('libs/alertifyjs/css/alertify.min.css'))
                          ->prependStylesheet($this->basePath('libs/datatables/extensions/Responsive/css/responsive.bootstrap.min.css'))
                          ->prependStylesheet($this->basePath('libs/datatables/extensions/Responsive/css/responsive.dataTables.min.css'))
                          ->prependStylesheet($this->basePath('libs/datatables/media/css/dataTables.bootstrap.min.css'))
                          ->prependStylesheet($this->basePath('libs/jquery-ui/jquery-ui.css'))
                          ->prependStylesheet($this->basePath('libs/font-awesome/css/font-awesome.min.css'))
                          ->prependStylesheet($this->basePath('libs/bootstrap/css/bootstrap.min.css'))
                          ->prependStylesheet($this->basePath('libs/bootstrap-switch/css/bootstrap-switch.css'))
                          ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,300,300italic,900,500,500italic,700italic,900italic')
                ?>

        <!-- Scripts -->
       <?php
       echo $this->headScript()
                    ->prependFile($this->basePath('libs/alertifyjs/alertify.min.js'))
                    ->prependFile($this->basePath('libs/jquery-validation/localization/messages_es.min.js'))
                    ->prependFile($this->basePath('libs/jquery-validation/jquery.validate.js'))            
                    ->prependFile($this->basePath('libs/jquery-ui/jquery-ui.min.js'))
                    ->prependFile($this->basePath('libs/bootstrap/js/bootstrap.min.js'))                       
                    ->prependFile($this->basePath('libs/bootstrap-switch/js/bootstrap-switch.min.js'))
                    ->prependFile($this->basePath('libs/datatables/media/js/jquery.dataTables.columnFilter.js'))
                    ->prependFile($this->basePath('libs/datatables/media/js/dataTables.bootstrap.min.js'))
                    ->prependFile($this->basePath('libs/datatables/extensions/Responsive/js/responsive.bootstrap.min.js'))
                    ->prependFile($this->basePath('libs/datatables/extensions/Responsive/js/dataTables.responsive.min.js'))
                    ->prependFile($this->basePath('libs/datatables/media/js/jquery.dataTables.min.js'))
                    ->prependFile($this->basePath('libs/prefixfree.min.js'))
                    ->prependFile($this->basePath('libs/jquery/jquery-1.11.3.min.js'))
        ; ?>

    </head>
    <body>         
            
            <?php echo $this->content; ?>

        <div class="clearBoth"></div>  
        <!-- /container -->  
        <?php echo $this->inlineScript();	
		
		
        ?>
    </body>
</html>
     