<div class="wrapper">      
	<div class="container">
		<div class="page-header">
			<h3>Subir archivos PM  <small></small></h3>  
		</div>
	  <div class="row">	     	
	  <div class="col-md-8 col-md-offset-2 panelUsr">         
         <div class="box-content-user">
         	
         	<div class="titUser text-center"> <h3>Empresas</h3> </div>    	
         	
          <div class="controlsInput text-center"> 
          	<form action="filepm/addFile"  enctype="multipart/form-data" id="MyUploadForm">           
          	 <select name="COMPANY" id="COMPANY" class="chosen-select form-control xlarge" data-msg="Nombre de la compañía es obligatorio.">     
               <option value="">- - Seleccione empresa- -</option>
               <?php foreach ($empresas as $combo) : ?>
               <option value="<?php echo $this->escapehtml($combo->CUSTOMER_ID);?>"><?php echo $this->escapehtml($combo->COMPANY);?></option>
               <?php endforeach; ?>  
             </select>
             
             <div class="errorMessage text-danger text-center"><span id="errorCOMPANY"></span></div>
            </div>  
		
         </div>    
       </div> 
		
	  </div>  	
	   
	   
	  <div id="contenDocument" class="row top-buffer">     	     	
	  <div class="col-md-8 col-md-offset-2 panelUsr">           
         <div class="box-content-user">
         	
          <div class="titUser text-center"> <h3>Tipo de Documento</h3> </div>          	
         	
          <div class="controlsInput text-center"> 
          	     
          	 <select name="DOCUMENTTYPE" id="DUCUMENTTYPE" class="chosen-type form-control xlarge">     
               <option value="">- - Seleccione un Tipo de Documento- -</option>
               <option value="Alcance comercial">Alcance comercial</option>     
               <option value="Kick Off">Kick Off</option>
               <option value="Carta de aceptacion">Carta de aceptación</option> 
               <option value="Plan de trabajo">Plan de trabajo</option>
               <option value="Minutas">Minutas</option>                
               <option value="Control de cambios">Control de cambios</option>
               <option value="Alcance tecnico">Alcance técnico</option>
               <option value="Base de datos">Base de datos</option>
               <option value="Tripticos de capacitacion">Tripticos de capacitación</option>     
             </select>              
             
           </div>    
         </div> 
         <div class="clearBoth"></div>       
       </div> 
		  
	  </div>
	   
	   <div class="uploadPM"> 
	    <div id="upload-wrapper">
		  <div align="center">
			<h3 class="titContraste"></h3>        
			  
			<input name="FileInput" id="FileInput" type="file" />
			<input type="button"  id="submit-btn" value="Subir Archivo" />     
			<img src="images/ajax-loader.gif" id="loading-img" style="display:none;" alt="Please Wait"/>
			</form>
			<div id="progressbox" ><div id="progressbar"></div ><div id="statustxt">0%</div></div>
			<div id="output"></div>
		 </div>
		</div>              
	   </div>
		
		
	</div><!--wrapper-->
</div><!-- container -->
<script>
/*chosen search */     
     $(".chosen-select").chosen({        
	  disable_search_threshold: 15,        
	  no_results_text: "Sin resultados para: ",    
						    
     });
     
	 $(".chosen-select").chosen().change(function() {
              
	   //alert($(this).text());   
	   var company = $("#COMPANY option:selected").text();
	   
	   //alert(company);      
	   $('#contenDocument').show();      
	   $(".chosen-type").chosen({            
	      disable_search_threshold: 15,        
	      no_results_text: "Sin resultados para: ",       
						    
       });
       
       $(".chosen-type").chosen().change(function() {
       	
       	var ducumenType = $("#DUCUMENTTYPE option:selected").text();
       	$('.titContraste').html(ducumenType);    
  	    $('.uploadPM').show();
  	    
  	});      
	        				         
  });  
    
  
	$(document).ready(function() {  
	
        
   	      $("#submit-btn").click(function(){ 
   	      	     
		//e.preventDefault();  
		 var form=$("#MyUploadForm"); 
		 var formVal = document.getElementById('MyUploadForm');
		 var formData = new FormData(formVal);
         //formData.append('FileInput', $('input[type=file]')[0].files[0]);        
         //formData.append('COMPANY',$('input[type=file]'))   
		$.ajax({   
        	url: $(form).attr('action'),   
			type: "POST",
			data: formData,          
			contentType: false,
    	    cache: false,    	      
			processData:false,      
			xhrFields: {     
		      // add listener to XMLHTTPRequest object directly for progress (jquery doesn't have this yet)
		     onprogress: function (e) {   
		      	    
              if(e.lengthComputable) {     
               //calculate the percentage loaded
                    var pct = (e.loaded / e.total) * 100;
                                         
                    $('#progressbox').show();
				    $('#progressbar').width(pct.toPrecision(3) + '%'); //update progressbar percent complete
				    $('#statustxt').html(pct.toPrecision(3) + '%'); //update status text
				    if(pct.toPrecision(3)>50)     
				        {
				            $('#statustxt').css('color','#000'); //change status text to white after 50%
				        }                                          
                }
                		      	
		      }
		 },            
					beforeSend : function()
			{     
							
				if (window.File && window.FileReader && window.FileList && window.Blob)
				{
					
					if( !$('#FileInput').val()) //verifica que no sea vacio
					{   
					    alertify.error("No has seleccionado ningún archivo.");
						return false;
						  
					}
					
					var fsize = $('#FileInput')[0].files[0].size; //Trae el tamaño del archivo 
					var ftype = $('#FileInput')[0].files[0].type; // Trae el tipo de archivo
					
			
					//Tipos permitidos
					switch(ftype)
			        {
			        //    case 'image/png': 
						//case 'image/gif': 
						//case 'image/jpeg': 
					//	case 'image/pjpeg':     
						case 'text/plain':
						case 'text/html':
						case 'application/x-zip-compressed':
						case 'application/pdf':
						case 'application/msword':
						case 'application/vnd.ms-excel':
						//case 'video/mp4':
			                break;
			            default:
			               alertify.error("Este tipo de archivo no es soportado <b>"+ftype+"</b>");                 
			              
						return false;
			        }
					
					//Maximo tamaño permitido 5 MB (1048576)
					if(fsize>5242880) 
					{
						alertify.error("<b>"+bytesToSize(fsize) +"El archivo es demasiado grande solo puedes subir 5 MB");
				    
						return false;
					}
							
					$('#submit-btn').hide(); //esconde el boton enviar
					$('#loading-img').show(); //esconde la imagen load
					$("#output").html("");  
				}
				else
				{
					//Error de salida a los navegadores sin soporte de más antiguos que no soporta HTML5 API Archivo
					alertify.error("Por favor, actualice su navegador, debido a que su navegador actual carece de algunas nuevas características que necesitamos!");
					return false;
				}
				
			},
			success: function(data)
		    {
		    	     
		    	 if (data.success === true) {   
                     alertify.success(data.message); 
                     
                     $('#submit-btn').show(); //hide submit button
					 $('#loading-img').hide(); //hide submit button
					 $('#progressbox').delay( 1000 ).fadeOut(); //hide progress bar  
                            
                     setTimeout(
					function() 
					{
						//location.href=data.url;    
					},1000);                                  	 
                                    
                 } else {
                 	 	
                   alertify.error(data.message);
                 }
		           
		    },
		  	error: function(e) 
	    	{     
				//$("#err").html(e).fadeIn();
				alertify.error("Algo no salió bien vuelve a intentarlo.");   
	    	} ,
	       	        
	   });
	   
	});   
	
	function bytesToSize(bytes) {
   var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
   if (bytes == 0) return '0 Bytes';
   var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1024)));
   return Math.round(bytes / Math.pow(1024, i), 2) + ' ' + sizes[i];
}	
	
});   
   	
</script>
