<?php ini_set("display_errors","on");?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sistema de Gestion CUAD</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONTAWESOME STYLES <link href="assets/css/font-awesome.css" rel="stylesheet" />-->  
     <link href="assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
       
    <!--TIMELINE STYLES-->
    <link href="assets/css/timeline.css" rel="stylesheet" />   
            
     <!-- CUSTOM STYLES-->
    <link href="assets/css/custom.css" rel="stylesheet" />
    <!-- SGC STYLES-->   
    <link href="assets/css/style.css" rel="stylesheet" />    
     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <!-- TABLE STYLES-->
    <link href="assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />  
</head>
<body>
    

   <div id="wrapper">  
<?php 
use Zend\Session\Container;
 $user_session = new Container('user'); 
 ini_set("display_errors","on");
echo $this->partial('resource/menu',array('nombreUsuario' => $user_session->username,
    'rol' => $user_session->rol,
    'email' => $user_session->email));

?>

   
    <div id="page-wrapper" >
            <div id="page-inner">         
       

   
      