<?php
$uri = $this->serverUrl(true);
$array=  explode('/', $uri);
$largo=count($array);
$menu=$array[$largo-1];
?>

<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>  
                </button>
                <span class="logo"><img src="assets/img/logoSGC.png" class="img-responsive"/></span>        
            </div>
            
  <div class="bienvenido" ><strong>BIENVENID@!</strong><br><?php echo strtoupper($this->nombreUsuario)?> <a href="logout" class="btn square-btn-adjust logout"><img src="assets/img/white-logout-256.png"></im></a> </div>
    </nav>   
          

 <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                <li class="text-center puesto">  
                   <?php echo $this->rol; ?>   
                </li>
                <li class="foto text-center">
                    <img src="assets/img/find_user.png" class="user-image img-responsive"/>
                </li>
                
                    
                    <li>
                        <a <?php if ($menu=="dashboard") {?>class="active-menu" <?php }?>  href="dashboard"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>   
                    </li>
                     <li>
                        <a <?php if ($menu=="empresas") {?>class="active-menu" <?php }?>  href="empresas"><i class="fa fa-industry fa-3x"></i> Empresas</a>  
                    </li><li>
                        <a <?php if ($menu=="sitios") {?>class="active-menu" <?php }?>   href="sitios"><i class="fa fa-fax fa-3x"></i> Sitios</a>  
                    </li>   
                      <li  >
                          <a <?php if ($menu=="fcs") {?>class="active-menu" <?php }?>  href="fcs"><i class="fa fa-file-pdf-o fa-3x"></i> FCS</a>
                    </li>                                 
                    <li>
                        <a <?php if ($menu=="notificaciones") {?>class="active-menu" <?php }?>  href="notificaciones"><i class="fa fa-comments fa-3x"></i> Notificaciones<!--<span class="fa arrow"></span>--></a>
                     
                      </li>  
                 <!-- <li>
                        <a  href="blank.html"><i class="fa fa-line-chart fa-3x"></i> Reportes</a>    
                    </li>  --> 
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->