<?php
 use Zend\Session\Container;
 $user_session = new Container('user');  
 $basepath=$this->basePath();       
?>
<div class="wrapper">   
	<div class="container">
	  <div class="page-header">    
		 <h3>FCS
		 	 
		 	 
		 	 
		 	 <?php if(!empty($nombreSitio)){
		 	 	    $messageEmpty = "<h3>No se ha agregado ningún fcs a este sitio</h3>";
		 	 	?>
				<small>Detalle de FCS's registrados del Sitio </small> <?php echo $nombreSitio->LOCATION_NAME; ?>      	 
												
				<?php }else{
					$messageEmpty = "<h3>No se ha agregado ningún fcs </h3>";   
					
					?>
						
				<small>Detalle de FCS's registrados</small></h3>
							
			<?php } ?>	
	  </div>
    <?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") { ?> 
      <div class="row">
         <div class="col-lg-3 col-md-6">
         <a href="<?php echo $this->url('fcs', array('action' => 'altas'));?>">	
            <div class="panel panel-primary">
               <div class="panel-heading">
                  <div class="row">
                     <div class="col-xs-3">
                        <i class="fa fa-file-pdf-o fa-5x"></i>
                     </div>
                     <div class="col-xs-9 text-right">
                        <div class="huge">+</div>
                        <div>Agregar FCS</div>
                     </div>
                  </div>
               </div>
               
                  <div class="panel-footer">
                     <span class="pull-left">Ver Más</span>
                     <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                     <div class="clearfix"></div>
                  </div>               
            </div>
            </a>
         </div>
      </div>
    <?php  } ?>     
              <?php if(!empty($fcss)){ ?>
             			
				<div class="datagrid">
					<table id="tableGrid" class="table table-responsive responsive table-stripe">
						<thead>
							<tr>
                                <th class="text-center">Empresa</th>
								<th class="text-center">Folio</th>
								<th class="text-center">Id del Sitio</th>
								<th class="text-center">Tipo Movimiento</th>
								<th class="text-center">Fecha Emisión</th>
								<th class="text-center">Tipo Servicio</th>
								<th class="text-center col-md-2">Acciones</th>  
								<?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") { ?>
								<th class="text-center col-md-2">Validación</th>		
							   <?php } ?>   
							</tr>
						</thead>
						<tbody>
                            <?php
                            $i=0;
                            
                             foreach ($fcss as $tabla) {                               	
						    ?>   
							<tr>   
                                                            
								<td><?php echo $fcss[$i]['COMPANY'];?></td>          
								<td><?php echo $this->escapehtml($fcss[$i]['FOLIO']);?></td>
								<td><?php echo $this->escapehtml($fcss[$i]['LOCATION_ID']);?></td>
								<td><?php echo $this->escapehtml($fcss[$i]['TIPOMOVIMIENTO']);?></td>
								<td><?php echo $this->escapehtml($fcss[$i]['FECHAEMISION']);?></td>
								<td><?php if($fcss[$i]['SERVICIO_ID']=="1"){ echo "CISCO";}
								          if($fcss[$i]['SERVICIO_ID']=="2"){ echo "BROADSOFT"; }       
								 ?></td>
								<td class="text-center">  
								<?php if ($user_session->rol == "Admin" || $user_session->rol == "Pedidos") { ?>  	
									<a href="<?php echo $this->url('fcs', array('action'=>'altas', 'id' => $fcss[$i]['SOLICITUD_ID']));?>" class="btn-accion btn-primary" title="Editar">     
										<i class="halflings-icon fa fa-pencil"></i>            
									</a>   
									<a data-id="<?php echo $this->escapehtml($fcss[$i]['CUSTOMER_ID']);?>" class="btn-accion btn-danger borrar" data-toggle="modal" data-target="#myModal" onclick="getFCS('<?php echo $this->escapehtml($fcss[$i]['SOLICITUD_ID']);?>');" title="Eliminar">   
										<i class="halflings-icon fa fa-trash"></i>         
									</a>																	 
								<?php } ?>	
									<a href="<?php echo $this->url('fcs', array('action'=>'detalle', 'id' => $fcss[$i]['SOLICITUD_ID']));?>" class="btn-accion btn-warning" title="Detalles">           
										<i class="halflings-icon fa fa-eye"></i>            
									</a>   
									
 								</td>
 								<?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") {
 									?>
 									
								<td class="text-center">
								<?php 
								   $validado= $fcss[$i]['VALIDADO'];
								   
								   if($validado>0){
								   	$btnAccion="btn-success";
									$fa="fa-thumbs-up";   
								   }else{
								   	$btnAccion ="btn-danger";
									$fa="fa-thumbs-down";     
								   }	  
									   
									    
								?>
								  <a data-id="<?php echo $this->escapehtml($fcss[$i]['SOLICITUD_ID']);?>" class="btn-accion <?php echo $btnAccion; ?>" data-toggle="modal" data-target="#modalValidateFcs"
								  	onclick="getValidateFCS('<?php echo $this->escapehtml($fcss[$i]['FOLIO']);?>','<?php echo $this->escapehtml($fcss[$i]['SOLICITUD_ID']);?>');" title="Validación">             
										<i class="halflings-icon fa <?php echo $fa; ?>"></i>                            
								  </a>   	
								</td>	 		
								<?php } ?>
 								   
							</tr>  
                               <?php 
                                 $i++;  
                                  } ?>  
						</tbody>
				  </table>	  
				</div> 
				<?php }else{?>  
				 <div class="row text-center">  
				   <?php echo $messageEmpty; ?>       
			     </div>  
				<?php	
				} ?>       
			</div><!--wrapper-->  
      
           <!--modal detalle FCS-->
            <div id="modalFcs" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridModalLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="gridModalLabel">Detalle FCS</h4>
			      </div>
			      <div class="modal-body">
			        <div class="container-fluid bd-example-row">
			         
				         <div class="row text-right">  
				         	<a href="#" class="btn-accion btn-info">       
							 <i class="halflings-icon fa fa-pencil-square-o"></i>              
							</a>	
				         </div>
			         
				         <div class="row">
						    <div class="col-md-4">Folio:</div>  
						    <div class="col-md-8 txtResalto">dasdas</div>  				    
					    </div>     
					     <div class="row">
						    <div class="col-md-4">Fecha de Emisión:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-2">QO:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-4">Cotización:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-4">Nombre del CAP:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-4">Email del CAP:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-4">Responsable de instalación (en sitio):</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">
						    <div class="col-md-4">Caso de Instalación:</div>
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					     <div class="row">   
						    <div class="col-md-4">Tel. Resp. en sitio:</div>    
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					    <div class="row">   
						    <div class="col-md-4">Tipo de servicio:</div>    
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					    <div class="row">   
						    <div class="col-md-4">Orden de aprovisionamiento:</div>    
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					    <div class="row">   
						    <div class="col-md-4">Tipo de Movimiento:</div>      
						    <div class="col-md-8 txtResalto"></div>				    
					    </div>
					    
					    <h3 class="text-center txtResalto">Servicios que se compran</h3>     
			       
							<table class="table table-bordered tblFcs">   
							  <thead>
							    <tr>
							      <th>Número de parte</th>
							      <th>Id de componente</th>
							      <th>Cantidad</th>
							      <th>Precio</th>
							    </tr>
							  </thead>
							  <tbody>
							    <tr>
							      <th scope="row">UNC.CUAD.BS.901</th>
							      <td>29242531</td>
							      <td>1</td>
							      <td>.01</td>   
							    </tr>
							    </tbody>
							</table>    
			            
			        </div>
			      </div>
			      <div class="clearBoth"></div>  
			     </div>
			                
			   </div>
			    
			  </div>
			
          <!--modal detalle FCS-->
          
         <?php if ($user_session->rol == "Admin" || $user_session->rol == "GerentePMO") { ?>
 									 
          <!--Modal validacion-->
           
           <div id="modalValidateFcs" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridModalLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="gridModalLabel">Validación FCS</h4>
			      </div>
			      <div class="modal-body">
			        <div class="container-fluid bd-example-row text-center">
			          <form name="validarFcs" id="validarFcs" method="post" action="">	  
			            <input type="hidden" name="idFCSval" id="idFCSval">
			            <div class="errorMessage text-danger"><span id="erroridFCSval"></span></div>
			            <h3>¿ Validar el FCS con el folio: <span style="font-weight: bold" name="folioFCS" id="folioFCS"></span> ?</h3><br><br>     
				        <button id="validando" type="submit" class="btn btn-success">Validar</button>   
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        
                      </form>    
			            
			        </div>
			      </div>
			      <div class="clearBoth"></div>  
			     </div>
			                
			   </div>
			    
			  </div>
          
          <!--Modal validacion-->
         <?php } ?>           
          
          <!--Load-->   
			    <div id="ark_loader-fcs" class="ark_loader">  
			      <span>CARGANDO</span>
			      <span>
			        <div class="sk-fading-circle">
			          <div class="sk-circle1 sk-circle"></div>
			          <div class="sk-circle2 sk-circle"></div>
			          <div class="sk-circle3 sk-circle"></div>
			          <div class="sk-circle4 sk-circle"></div>
			          <div class="sk-circle5 sk-circle"></div>
			          <div class="sk-circle6 sk-circle"></div>
			          <div class="sk-circle7 sk-circle"></div>
			          <div class="sk-circle8 sk-circle"></div>
			          <div class="sk-circle9 sk-circle"></div>
			          <div class="sk-circle10 sk-circle"></div>
			          <div class="sk-circle11 sk-circle"></div>
			          <div class="sk-circle12 sk-circle"></div>
			        </div>
			      </span>  
			    </div>  
			    <!--load-->      
          
      
      </div><!--container container-fluid-->          
      
      
      
      <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <form name="borraFcs" id="borraFcs" method="post" action="">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Borrar FCS</h4>
      </div>
      <div class="modal-body">
      <p>¿Está seguro de eliminar el Fcs CON id  <span style="font-weight: bold" name="FCS" id="FCS"></span>?</p>
      </div>
        <div class="errorMessage text-danger"><span id="erroridFCS"></span></div>
        <input type="hidden" name="idFCS" id="idFCS"></input>
      <div class="modal-footer">
          
          <button id="borrando" type="submit" class="btn btn-primary">Eliminar</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
    </form>
  </div>
</div>
   
      
    <script type="text/javascript">
      
				$(window).load(function() {
					// Animate loader off screen
					$("#ark_loader-fcs").fadeOut("slow");       
				});
 	
                  function getFCS(ID)
                  {
                    
                    $('#FCS').html(ID);  
                    $('#idFCS').html(ID); 
                  
                     var link='<?php echo $basepath;?>/fcs/borrar/'+ID;    
                     //alert(link);
                     $('#borraFcs').attr("action", link);
                  }
                  
                  function getValidateFCS(FOLIO,ID)
                  {
                    
                    $('#folioFCS').html(FOLIO);    
                    $('#idFCSval').val(ID);     
                  
                   var link='<?php echo $basepath;?>/fcs/validar/'+ID;        
                     //alert(link);
                     $('#validarFcs').attr("action", link);      
                  }
                 
                  
                  
                $(document).ready(function(){
                    $('.borrar').click(function() {                    
                    var $this=$(this);     
                    
                    var ID = $this.attr('data-id');
                    //alert(ID);
                     
                    
                    });
                });
              
                 
			(function(){
				//$("table").dataTable();
				
				/*tabla Grid*/
			   $('#tableGrid').DataTable( {
			       /* "scrollX": true,*/     
			        "language": {
			                "sProcessing":     "Procesando...",
			                "sLengthMenu":     "Mostrar _MENU_ registros",
			                "sZeroRecords":    "No se encontraron resultados",
			                "sEmptyTable":     "Ningún dato disponible en esta tabla",
			                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
			                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
			                "sInfoPostFix":    "",
			                "sSearch":         "Buscar:",
			                "sUrl":            "",
			                "sInfoThousands":  ",",
			                "sLoadingRecords": "Cargando...",
			                "oPaginate": {
			                    "sFirst":    "Primero",
			                    "sLast":     "Último",
			                    "sNext":     "Siguiente",
			                    "sPrevious": "Anterior"
			                },
			                "oAria": {
			                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
			                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
			                }
			          }   
			    } );
				
			})(this);


		</script>   

<?php 
   echo $this->headScript()->prependFile($this->basePath('/js/fcs.js'));
   ?>   	
      