<?php //print_r($allPM); 

//echo $allPM[0]['mail'];   	

 

 

?>        
<div class="wrapper">   
   <div class="container">
      <div class="page-header">
         <h3>Asignación de usuarios<small> Vincular un PM a una empresa</small></h3>
      </div>
      <!--page-header-->
      <div class="row col-md-8 col-md-offset-2 panelUsr">         
         <div class="box-content-user">  
         	         	 
          <div class="titUser text-center"> <h3>Usuarios PM</h3> </div>  
            
           <div class="control-group-user">
           	<?php
           	   for ($i=0; $i < $totalPM; $i++) {
           	 ?>  
           	    <div class="controlsInput">  	 
			     <input type="radio" value="<?php echo $allPM[$i]['mail']; ?>" /> <?php echo $allPM[$i]['name']; ?>
			    </div> 				
			<?php 		     
				}
           	?>     
           </div> 
             	 
          
           <form name="fcs" id="fcs" class="form-horizontal" action="" method="post">                      
              
             <div class="control-group">
             </div>   
                
             <div class="control-group btnAddUser text-right">          
               <button class="btn btn-info btn-enviar" type="submit"><i class="fa fa-user-plus" aria-hidden="true"></i> Asignar Usuario </button>         
             </div>
            </form>
               
         </div>
      </div>
      
     
      
      
   </div><!--conteiner-->      
   
   <div id="ark_loader-login" class="ark_loader hidden">
	    <span>CARGANDO</span>
			<span>
			<div class="sk-fading-circle">
				<div class="sk-circle1 sk-circle"></div>
				<div class="sk-circle2 sk-circle"></div>
				<div class="sk-circle3 sk-circle"></div>
				<div class="sk-circle4 sk-circle"></div>
				<div class="sk-circle5 sk-circle"></div>
				<div class="sk-circle6 sk-circle"></div>
				<div class="sk-circle7 sk-circle"></div>
				<div class="sk-circle8 sk-circle"></div>
				<div class="sk-circle9 sk-circle"></div>
				<div class="sk-circle10 sk-circle"></div>
				<div class="sk-circle11 sk-circle"></div>
				<div class="sk-circle12 sk-circle"></div>
			</div>
		</span>  
	</div>
   
      
</div>
<!--wrapper-->

<?php 
  //echo $this->headScript()->appendFile($this->basePath('/js/fcs.js'));    
?>

