<?php  if(!empty($sitio)){ ?>
<div class="datagrid">  
					<table id="tableGridDta" class="table table-responsive responsive table-stripe">
						<thead>
							<tr>
								<th class="text-center">Número sitio    </th>
								<th class="text-center">Nombre del sitio</th>
								<th class="text-center">Tipo de servicio </th>   
                                <th class="text-center">Número de extensiones</th>
								<th class="text-center">Extensiones por aprovisionar</th>
								<th class="text-center">Extensiones aprovisionadas</th>
                                      
							</tr>
						</thead>
					<tbody>
                       <?php
                     
                       foreach ($sitio as $tabla) { 
                       	?>   
                       <?php //if($this->escapehtml($tabla->COMPANY)=="") {continue;}?>
							<tr>
								<td><?php echo $this->escapehtml($tabla["LOCATION"]);?></td>       
								<td><?php echo $this->escapehtml($tabla["LOCATION_NAME"]);?></td>      
								<td><?php 
								     if ($tabla["SERVICIO_ID"]==1){echo "CUAD-CISCO"; }
								     if ($tabla["SERVICIO_ID"]==2){echo "CUAD-BROADSOFT"; }  									
									?></td>        
								<td></td>
								<td></td>
								<td></td>
							</tr>  
                       <?php } ?>                  
					 </tbody>
                  </table>
				</div> 
	 
        <?php }else{
         ?>   
         <h2>No hay sitios registrados en esta empresa</h2>     
         <?php
        }?>   			 
<script>
	

  
		

   $('#tableGridDta').DataTable( {  
			       /* "scrollX": true,*/     
			        "language": {
			                "sProcessing":     "Procesando...",
			                "sLengthMenu":     "Mostrar _MENU_ registros",
			                "sZeroRecords":    "No se encontraron resultados",
			                "sEmptyTable":     "Ningún dato disponible en esta tabla",
			                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
			                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
			                "sInfoPostFix":    "",
			                "sSearch":         "Buscar:",
			                "sUrl":            "",
			                "sInfoThousands":  ",",
			                "sLoadingRecords": "Cargando...",
			                "oPaginate": {
			                    "sFirst":    "Primero",
			                    "sLast":     "Último",
			                    "sNext":     "Siguiente",
			                    "sPrevious": "Anterior"
			                },
			                "oAria": {
			                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
			                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
			                }
			          }   
			    } );	
	 		    
	
</script>				
      	